name: CI/CD for Docker Swarm Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Frontend Image
        run: |
          cd frontend
          docker build -t my-app-frontend .
        
      - name: Build Backend Image
        run: |
          cd backend
          docker build -t my-app-backend .
        
      - name: Push Images to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker tag my-app-frontend $DOCKER_USERNAME/my-app-frontend
          docker tag my-app-backend $DOCKER_USERNAME/my-app-backend
          docker push $DOCKER_USERNAME/my-app-frontend
          docker push $DOCKER_USERNAME/my-app-backend
